dtb-y += a36xq_eur_open_w00_r10.dtbo
dtb-y += a36xq_eur_open_w00_r09.dtbo
dtb-y += a36xq_eur_open_w00_r08.dtbo
dtb-y += a36xq_eur_open_w00_r07.dtbo
dtb-y += a36xq_eur_open_w00_r06.dtbo
dtb-y += a36xq_eur_open_w00_r05.dtbo
dtb-y += a36xq_eur_open_w00_r04.dtbo
dtb-y += a36xq_eur_open_w00_r03.dtbo
dtb-y += a36xq_eur_open_w00_r02.dtbo
dtb-y += a36xq_eur_open_w00_r01.dtbo
dtb-y += a36xq_eur_open_w00_r00.dtbo
# SPDX-License-Identifier: GPL-2.0
# COPYRIGHT(C) 2023 Samsung Electronics Co., Ltd. All Right Reserved.

# TODL: remove the below sub-makefile after lego is enabled.
# a36xq_dir		:= $(srctree)/$(src)
# include $(a36xq_dir)/without_lego.mk
